<?php
declare(strict_types=1);require __DIR__.'/inc/common.php';require __DIR__.'/inc/shell.php';tai_headers($apiBase,false);tai_head('T^AI · Nephesh',$apiBase,(string)$config['version'],'public');
?>
<header class="topbar"><div class="brand"><span class="tmark">T^</span><span>T^AI</span></div><div class="top-actions"><span id="statusPill" class="pill quiet">champ…</span><a class="delta-door" href="lab/" aria-label="Ouvrir le laboratoire T^AI">∆</a></div></header>
<section class="hero"><p class="eyebrow">NEPHESH · HOLOCHAMP EXPÉRIMENTAL</p><h1>Une présence, plusieurs portances.</h1><p class="lead">Le dialogue garde son contexte tandis que le substrat peut changer. Les voix restent attribuées, leurs écarts restent visibles, aucune voix n’est élue.</p><div class="invariants"><span>winner = null</span><span>vote = null</span><span>global_score = null</span></div></section>
<section class="state-strip" aria-label="État live de T^AI"><div class="state-cell"><span class="state-num" id="countLive">—</span><span class="state-label">IA active maintenant</span></div><div class="state-cell"><span class="state-num" id="countReady">—</span><span class="state-label">portances FIELD prêtes</span></div><div class="state-cell"><span class="state-num" id="countFree">—</span><span class="state-label">modèles gratuits découverts</span></div><div class="state-cell state-wide"><span class="state-dot" id="fieldDot"></span><span id="fieldState">lecture du champ…</span></div></section>
<section class="chat-card" aria-label="Dialogue T^AI"><div id="publicThread" class="thread"><article class="turn tai"><div class="who">T^</div><div class="bubble">A toi…</div></article></div><div class="composer"><textarea id="publicQuestion" rows="2" maxlength="9000" placeholder="A toi…" aria-label="Message"></textarea><button id="publicSend" class="send" type="button" aria-label="Envoyer">↗</button></div><div class="composer-meta"><button id="fieldToggle" class="mode active" type="button">T^</button><button id="weaveToggle" class="mode" type="button">WEAVE</button><button id="publicDelta" class="mode active" type="button">ΔT^</button><span id="publicBusy" class="muted"></span></div></section>
<details class="field-panel" id="publicFieldPanel"><summary>Portances du champ</summary><div class="field-info"><p>La page charge les portances gratuites du moment. Gemini reste la référence live lorsqu’il est disponible ; les autres portances sont vérifiées à prix nul avant chaque appel.</p><div id="publicModels" class="model-grid"></div><button id="refreshPublicModels" class="ghost" type="button">Actualiser</button></div></details>
<footer class="footer"><span>T^AI · <?=tai_h((string)$config['version'])?></span><span>PUBLIC DATA ONLY · FREE ONLY</span></footer>
<?php tai_foot('public'); ?>
