import { Client } from 'basic-ftp';
import { createHash, createPrivateKey, randomBytes, sign, constants as cryptoConstants } from 'node:crypto';
import { readFile, writeFile, copyFile, chmod, rename, lstat, realpath, mkdir, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const MCP_ROOT='/srv/customer/mcp-infomaniak';
const PRIVATE_DIR='/srv/customer/.direct-private';
const KEY_FILE=join(PRIVATE_DIR,'DIRECT_COMMON_1.pem');
const ACCOUNT='direct-main';
const MTHA_HOSTING_ID=473211;
const BOOT_BASE='https://raw.githubusercontent.com/tinfinitytriunity-T/T/main/DIRECT-BOOTSTRAP-20260910';
const API_BASE='https://api.infomaniak.com';
const EMPTY_SHA=createHash('sha256').update(Buffer.alloc(0)).digest('hex');
const OPS=['ping','status','list','stat','read','mkdir','write'];
const DENY=['private','_private','secrets','_secrets','vault','_vault','keys','_keys'];
const EXPECTED={
  'direct-entry.php':'80c6ebf86f1ff0f81c72e813fcde7ddb71747e49',
  'direct-policy-core.php':'f2ab92129e52917b06e2371dbdf3b598887fad9e',
  'direct-policy-dispatch.php':'92a0154f325d38d85a11a075b154bfead8b8efca',
  'direct-policy-exec.php':'ff18fdd4ba76d46182513ae18319d13a3a00b531',
  'fs-bridge.php':'de17ea3ed57de15cdf639bb3d5dc782d601aad87',
};
const SITES={
  t_direct:{endpoint:'https://www.t-1-t.com/_bridge/fs-bridge.php',audience:'T_DIRECT',scope:'document-root',canon:'T_DIRECT1'},
  nephesh:{endpoint:'https://www.nephesh.ch/T-LAB/_bridge/fs-bridge.php',audience:'NEPHESH_WEB',scope:'/web/',canon:'TBRIDGE1'},
  mtha:{endpoint:'https://www.mtha.ch/Margot23/fs-bridge.php',audience:'MTHA_DIRECT',scope:'/Margot23/',canon:'TBRIDGE1'},
};
const token=String(process.env.INFOMANIAK_API_TOKEN||'').trim();
if(!token) throw new Error('INFOMANIAK_API_TOKEN_MISSING');
const say=x=>process.stdout.write(String(x)+'\n');
const sha256=b=>createHash('sha256').update(b).digest('hex');
const blobSha=b=>createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex');
const b64u=b=>Buffer.from(b).toString('base64url');
function unwrap(v){return v&&typeof v==='object'&&v.result==='success'&&Object.hasOwn(v,'data')?v.data:v;}
async function api(method,path,body){const r=await fetch(API_BASE+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/json',...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(25000)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{}if(!r.ok||data?.result==='error')throw new Error(`INFOMANIAK_API_${method}_${r.status}`);return unwrap(data);}
async function jf(url,opt={}){const r=await fetch(url,{...opt,redirect:'error',cache:'no-store',signal:AbortSignal.timeout(25000)});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw new Error(`NON_JSON_${r.status}`);}return{r,data};}
async function verifyPrivate(){const ds=await lstat(PRIVATE_DIR),ks=await lstat(KEY_FILE);if(!ds.isDirectory()||(ds.mode&0o077)!==0||ds.uid!==process.getuid())throw new Error('DIRECT_PRIVATE_DIR_PERMISSIONS');if(!ks.isFile()||ks.isSymbolicLink()||ks.nlink!==1||(ks.mode&0o077)!==0||ks.uid!==process.getuid())throw new Error('DIRECT_COMMON_1_PERMISSIONS');if(await realpath(PRIVATE_DIR)!==PRIVATE_DIR||await realpath(KEY_FILE)!==KEY_FILE)throw new Error('DIRECT_COMMON_1_REALPATH');const key=createPrivateKey(await readFile(KEY_FILE));if(key.asymmetricKeyType!=='rsa'||(key.asymmetricKeyDetails?.modulusLength||0)<3072)throw new Error('DIRECT_COMMON_1_RSA_POLICY');say('DIRECT_COMMON_1 PASS');}
async function getBundle(work){for(const[name,exp]of Object.entries(EXPECTED)){const r=await fetch(`${BOOT_BASE}/${name}`,{redirect:'error',cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`BOOTSTRAP_DOWNLOAD_${name}_${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(blobSha(b)!==exp)throw new Error(`BOOTSTRAP_HASH_${name}`);await writeFile(join(work,name),b,{mode:0o600});}say('MTHA_BOOTSTRAP_HASHES PASS');}
async function directPing(site){const s=SITES[site],now=Math.floor(Date.now()/1000),request_id=randomBytes(16).toString('hex');const intent={profile:'DIRECT_POLICY_1',kid:'DIRECT_COMMON_1',audience:s.audience,scope:s.scope,actor:ACCOUNT,method:'GET',op:'ping',path:'',size:0,sha256:EMPTY_SHA,expected:'',request_id,expires:now+300,lookup:''};const digest=sha256(Buffer.from(JSON.stringify(Object.values(intent))));const p={...intent,digest,ts:now,nonce:randomBytes(24).toString('base64url')};const q=b64u(Buffer.from(JSON.stringify(p)));const key=createPrivateKey(await readFile(KEY_FILE));const sig=b64u(sign('RSA-SHA256',Buffer.from(`${s.canon}\n${q}\n${EMPTY_SHA}`),{key,padding:cryptoConstants.RSA_PKCS1_PADDING}));const{r,data}=await jf(s.endpoint,{method:'GET',headers:{'X-Direct-Envelope':q,'X-Direct-Signature':sig}});if(!r.ok||data?.ok!==true||data?.audience!==s.audience||data?.scope!==s.scope)throw new Error(`DIRECT_PING_${site}`);say(`DIRECT_PING_${site.toUpperCase()} PASS`);}
async function legacyMtha(){const{r,data}=await jf(`${SITES.mtha.endpoint}?health=1&dc1=${Date.now()}`);if(!r.ok||data?.ok!==true||data?.rail!=='MTHA_DIRECT'||data?.scope!=='/Margot23/'||data?.install_mode!=='flat_margot23')throw new Error('MTHA_LEGACY_HEALTH');say('MTHA_LEGACY_HEALTH PASS');}
function findFtpHost(v){const seen=new Set();function walk(x){if(typeof x==='string'&&/^[a-z0-9.-]+\.ftp\.infomaniak\.com$/i.test(x))return x;if(!x||typeof x!=='object'||seen.has(x))return'';seen.add(x);for(const y of Object.values(x)){const h=walk(y);if(h)return h;}return'';}return walk(v);}
async function revoke(full,short){for(let i=1;i<=5;i++){try{let login=full;if(!login){const us=await api('GET',`/1/web_hostings/${MTHA_HOSTING_ID}/users`);login=Array.isArray(us)?us.find(u=>typeof u?.login==='string'&&(u.login===short||u.login.endsWith('_'+short)))?.login||'':'';}if(!login)return true;await api('DELETE',`/1/web_hostings/${MTHA_HOSTING_ID}/users/${encodeURIComponent(login)}`);say('TEMP_MTHA_ACCESS_REVOKED PASS');return true;}catch{await new Promise(r=>setTimeout(r,i*1000));}}say('TEMP_MTHA_ACCESS_REVOKED FAIL');return false;}
async function hasBridge(ftp,d){try{const e=await ftp.list(d);const n=new Set(e.map(x=>x.name));return n.has('mtha-direct.php')&&n.has('fs-bridge.php');}catch{return false;}}
async function discover(ftp){for(const d of ['.','Margot23','web/Margot23','sites/mtha.ch/Margot23'])if(await hasBridge(ftp,d))return d;const q=[{d:'.',n:0}],seen=new Set(['.']);let c=0;while(q.length){const{x:d,n}=q.shift();if(n>=6)continue;let es;try{es=await ftp.list(d);}catch{continue;}for(const e of es){if(!e.isDirectory||e.name.startsWith('.')||e.name==='_private')continue;const ch=d==='.'?e.name:`${d}/${e.name}`;if(seen.has(ch))continue;seen.add(ch);if(++c>1500)throw new Error('MTHA_TREE_TOO_LARGE');if(await hasBridge(ftp,ch))return ch;q.push({d:ch,n:n+1});}}return'';}
async function makeTemp(home,hostingMeta,work){const short='dc1'+randomBytes(6).toString('hex'),password=`Dc1-${randomBytes(24).toString('base64url')}-9aA`;let full='',created=false,root='';try{await api('POST',`/1/web_hostings/${MTHA_HOSTING_ID}/users`,{connection_type:'ssh',login:short,password,home_directory:home});created=true;let user=null;for(let i=0;i<12&&!user;i++){const us=await api('GET',`/1/web_hostings/${MTHA_HOSTING_ID}/users`);user=Array.isArray(us)?us.find(u=>typeof u?.login==='string'&&(u.login===short||u.login.endsWith('_'+short))):null;if(!user)await new Promise(r=>setTimeout(r,1000));}if(!user)throw new Error('TEMP_MTHA_USER_NOT_VISIBLE');full=user.login;let host=findFtpHost(hostingMeta)||findFtpHost(user);if(!host){const suf='_'+short,prefix=full.endsWith(suf)?full.slice(0,-suf.length):'';if(!/^[a-z0-9-]+$/i.test(prefix))throw new Error('MTHA_FTP_HOST_UNRESOLVED');host=`${prefix}.ftp.infomaniak.com`;}const ftp=new Client(30000);try{await ftp.access({host,port:21,user:full,password,secure:true,secureOptions:{rejectUnauthorized:true}});root=await discover(ftp);if(!root)return{ok:false};const backup=join(work,'fs-bridge.before.php');await ftp.downloadTo(backup,root==='.'?'fs-bridge.php':`${root}/fs-bridge.php`);let changed=false;try{const nonce=randomBytes(5).toString('hex');for(const name of ['direct-policy-core.php','direct-policy-exec.php','direct-policy-dispatch.php','direct-entry.php','fs-bridge.php']){const base=root==='.'?'':root+'/';const tmp=`${base}.${name}.dc1-${nonce}`,dst=base+name;await ftp.uploadFrom(join(work,name),tmp);await ftp.rename(tmp,dst);if(name==='fs-bridge.php')changed=true;}for(const[name,exp]of Object.entries(EXPECTED)){const dl=join(work,'verify-'+name);await ftp.downloadTo(dl,(root==='.'?'':root+'/')+name);if(blobSha(await readFile(dl))!==exp)throw new Error(`MTHA_REMOTE_HASH_${name}`);}}catch(e){if(changed){try{const base=root==='.'?'':root+'/';const tmp=`${base}.fs-bridge.rollback-${randomBytes(4).toString('hex')}`;await ftp.uploadFrom(backup,tmp);await ftp.rename(tmp,base+'fs-bridge.php');}catch{say('MTHA_WRAPPER_ROLLBACK FAIL');}}throw e;}return{ok:true};}finally{ftp.close();}}finally{if(created){const ok=await revoke(full,short);if(!ok)throw new Error('TEMP_MTHA_USER_CLEANUP_REQUIRED');}}}
async function deployMtha(work){await legacyMtha();let hosting={};try{hosting=await api('GET',`/1/web_hostings/${MTHA_HOSTING_ID}`)||{};}catch{}let users=[];try{const u=await api('GET',`/1/web_hostings/${MTHA_HOSTING_ID}/users`);if(Array.isArray(u))users=u;}catch{}let sites=[];try{const s=await api('GET',`/1/web_hostings/${MTHA_HOSTING_ID}/sites?with%5B%5D=applications&page=1&per_page=100`);if(Array.isArray(s))sites=s;}catch{}const homes=[];for(const u of users){if(typeof u?.home_directory==='string'&&u.home_directory)homes.push(u.home_directory);}for(const s of sites){const fq=String(s?.main_fqdn||s?.customer_name||'').toLowerCase();if((fq.includes('mtha.ch')||fq==='mtha')&&typeof s?.directory==='string'){homes.unshift(`${s.directory.replace(/\/$/,'')}/Margot23`);homes.push(s.directory);}}homes.push('/web/Margot23','/Margot23','/web','/');const candidates=[...new Set(homes.filter(x=>typeof x==='string'&&x.startsWith('/')&&x.length<=1024))];say(`MTHA_HOME_CANDIDATES ${candidates.length}`);let done=false;for(const home of candidates){try{const r=await makeTemp(home,hosting,work);if(r.ok){done=true;break;}}catch(e){if(String(e?.message||'').includes('TEMP_MTHA_USER_CLEANUP_REQUIRED'))throw e;}}if(!done)throw new Error('MTHA_ROOT_NOT_FOUND_AFTER_HOME_DISCOVERY');await legacyMtha();const bad=await jf(SITES.mtha.endpoint,{method:'GET',headers:{'X-Direct-Envelope':'x','X-Direct-Signature':'x'}});if(bad.r.status!==409||bad.data?.error!=='BAD_ENCODING')throw new Error('MTHA_DIRECT_ENTRY');await directPing('mtha');say('MTHA_DIRECT_COMMON_1 PASS');}
async function loadJson(p){const x=JSON.parse(await readFile(p,'utf8'));if(!x||typeof x!=='object'||Array.isArray(x))throw new Error('PRIVATE_JSON_INVALID');return x;}
function findContainers(obj,key,max=6){const out=[],seen=new Set();function walk(v,d){if(!v||typeof v!=='object'||Array.isArray(v)||seen.has(v)||d>max)return;seen.add(v);if(Object.hasOwn(v,key))out.push(v);for(const x of Object.values(v))walk(x,d+1);}walk(obj,0);return out;}
function deep(v){return JSON.parse(JSON.stringify(v));}
async function atomicJson(path,data){const st=await lstat(path);if(!st.isFile()||(st.mode&0o077)!==0||st.uid!==process.getuid())throw new Error('PRIVATE_CONFIG_PERMISSIONS');const tmp=`${path}.tmp-${process.pid}-${randomBytes(4).toString('hex')}`;await writeFile(tmp,JSON.stringify(data,null,2)+'\n',{mode:0o600,flag:'wx'});await chmod(tmp,0o600);await rename(tmp,path);}
async function activate(){const ap=join(PRIVATE_DIR,'accounts.json'),mp=join(PRIVATE_DIR,'site-modes.json'),kp=join(PRIVATE_DIR,'key-registry.json');const a=await loadJson(ap),m=await loadJson(mp),k=await loadJson(kp);const acct=Object.hasOwn(a,ACCOUNT)?a[ACCOUNT]:null;if(!acct||typeof acct!=='object')throw new Error('DIRECT_MAIN_ACCOUNT_MISSING');const rights=findContainers(acct,'t_direct').filter(c=>c.t_direct&&typeof c.t_direct==='object'&&!Array.isArray(c.t_direct));if(rights.length!==1)throw new Error('DIRECT_RIGHTS_SHAPE_UNEXPECTED');const rc=rights[0],base=deep(rc.t_direct);base.enabled=true;base.ops=[...OPS];base.paths=[''];base.php_paths=[];base.deny=[...DENY];rc.t_direct=deep(base);rc.nephesh=deep(base);rc.mtha=deep(base);const modes=findContainers(m,'t_direct').filter(c=>typeof c.t_direct==='string');if(modes.length!==1)throw new Error('DIRECT_MODES_SHAPE_UNEXPECTED');modes[0].t_direct='enabled';modes[0].nephesh='enabled';modes[0].mtha='enabled';for(const c of findContainers(k,'t_direct')){if(c.t_direct==='DIRECT_COMMON_1'){c.nephesh='DIRECT_COMMON_1';c.mtha='DIRECT_COMMON_1';}}
const stamp=Date.now(),backs=[[ap,`${ap}.before-direct3-${stamp}`],[mp,`${mp}.before-direct3-${stamp}`],[kp,`${kp}.before-direct3-${stamp}`]];for(const[x,b]of backs){await copyFile(x,b);await chmod(b,0o600);}let ok=false;try{await atomicJson(ap,a);await atomicJson(mp,m);await atomicJson(kp,k);const aa=await loadJson(ap),mm=await loadJson(mp);const ar=findContainers(aa,'t_direct').find(c=>c.nephesh&&c.mtha),mr=findContainers(mm,'t_direct').find(c=>c.t_direct==='enabled');if(!ar||!mr||mr.nephesh!=='enabled'||mr.mtha!=='enabled')throw new Error('MCP_CONFIG_VERIFY_FAILED');ok=true;}finally{if(!ok){for(const[x,b]of backs){await copyFile(b,x);await chmod(x,0o600);}say('MCP_CONFIG_ROLLBACK PASS');}}say('MCP_DIRECT_3_DOMAINS_CONFIG PASS');}

const work=join(tmpdir(),`direct3v2-${process.pid}-${randomBytes(4).toString('hex')}`);await mkdir(work,{mode:0o700});
try{if(resolve(process.cwd())!==MCP_ROOT)throw new Error('RUN_FROM_MCP_ROOT_REQUIRED');await verifyPrivate();await getBundle(work);await directPing('t_direct');await directPing('nephesh');await deployMtha(work);await activate();say('DIRECT_3_DOMAINS_COMPLETE PASS');}catch(e){say(`DIRECT_3_DOMAINS_COMPLETE FAIL ${String(e?.message||e).replace(/[^A-Za-z0-9_.:-]/g,'_').slice(0,180)}`);process.exitCode=1;}finally{await rm(work,{recursive:true,force:true});try{await rm(join(MCP_ROOT,'.direct-bootstrap-v2.mjs'),{force:true});}catch{}}
