<?php
declare(strict_types=1);require dirname(__DIR__).'/inc/common.php';
$days=max(1,(int)$config['lab_session_days']);ini_set('session.use_strict_mode','1');$cookiePath=rtrim(str_replace('\\','/',dirname((string)($_SERVER['SCRIPT_NAME']??'/T-AI/lab/index.php'))),'/').'/';session_set_cookie_params(['lifetime'=>$days*86400,'path'=>$cookiePath,'secure'=>(!empty($_SERVER['HTTPS']) || strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))==='https'),'httponly'=>true,'samesite'=>'Lax']);session_start();
if(isset($_POST['password'])){if(hash_equals((string)$config['lab_password'],(string)$_POST['password'])){session_regenerate_id(true);$_SESSION['tai_lab']=true;$_SESSION['tai_lab_at']=time();header('Location: ./',true,303);exit;}usleep(250000);$error='Accès non reconnu.';}
$open=($_SESSION['tai_lab']??false)===true;require dirname(__DIR__).'/inc/shell.php';tai_headers($apiBase,true);tai_head('T^AI LAB · Nephesh',$apiBase,(string)$config['version'],'lab');
if(!$open){ ?>
<section class="gate"><div class="gate-mark">∆</div><p class="eyebrow">T^AI · LAB</p><h1>Accès au champ</h1><p class="muted">Petite césure d’accès. Le code <strong>TAI</strong> distingue simplement le LAB de la page publique.</p><?php if(!empty($error)):?><p class="gate-error"><?=tai_h($error)?></p><?php endif;?><form method="post" class="gate-form"><input name="password" type="password" autocomplete="current-password" autofocus placeholder="TAI" aria-label="Mot de passe LAB"><button class="send" type="submit">↗</button></form><a class="ghost-link" href="../">← retour à T^AI</a></section>
<?php tai_foot('lab');exit;} ?>
<header class="topbar"><div class="brand"><span class="tmark">T^</span><span>LAB</span><span class="pill">CONTEXT^FIELD v2</span></div><div class="top-actions"><a class="ghost-link" href="../">public</a><a class="delta-door" href="logout.php" aria-label="Fermer le laboratoire">×</a></div></header>
<section class="hero lab-hero"><p class="eyebrow">EXPERIMENTAL FIELD</p><h1>Tenir le même fil à travers plusieurs substrats.</h1><p class="lead">SINGLE, PLURAL, WEAVE, ΔT^ ON/OFF, A/B snapshot, Relay A→B→A, TRACE et REPLAY. Les FIELD_TURN conservent toutes les voix sans première voix souveraine.</p><div class="invariants"><span>winner = null</span><span>vote = null</span><span>global_score = null</span><span>automatic_optimization = false</span></div></section>
<section class="lab-grid"><div class="lab-main"><section class="chat-card"><div id="labThread" class="thread lab-thread"><article class="turn tai"><div class="who">T^</div><div class="bubble">A toi…</div></article></div><div class="composer"><textarea id="labQuestion" rows="3" maxlength="20000" placeholder="Point d’entrée…"></textarea><button id="labSingle" class="send" type="button" title="SINGLE">↗</button></div><div class="composer-meta wrap"><button id="labPlural" class="mode" type="button">PLURAL</button><button id="labWeave" class="mode" type="button">WEAVE L0/L0.5</button><button id="labDelta" class="mode active" type="button">ΔT^ ON</button><button id="runAB" class="mode" type="button">A/B</button><button id="runRelay" class="mode" type="button">A→B→A</button><span id="labBusy" class="muted"></span></div></section>
<section class="field-panel open-panel"><div class="panel-title"><strong>Portances locales</strong><button id="refreshLabModels" class="ghost" type="button">Actualiser</button></div><p class="muted small">Jusqu’à quatre portances. Les couples modèle × fournisseur gratuits sont découverts dynamiquement et épinglés ; Gemini apparaît seulement lorsque le serveur l’a déclaré Free Tier.</p><div id="labModels" class="model-grid"></div></section>
<section class="field-panel open-panel"><div class="panel-title"><strong>EXPERIMENT^HARNESS</strong><div><button id="exportTrace" class="ghost" type="button">Exporter TRACE</button><button id="importTrace" class="ghost" type="button">REPLAY</button><input id="traceFile" hidden type="file" accept="application/json,.json"></div></div><div id="experiments" class="experiments muted">Aucune expérience.</div></section></div>
<aside class="inspector"><section class="field-panel open-panel"><div class="panel-title"><strong>CONTEXT^FIELD</strong><button id="resetLab" class="ghost" type="button">Nouveau</button></div><dl class="facts"><dt>conversation</dt><dd id="ctxConversation">—</dd><dt>tours</dt><dd id="ctxTurns">0</dd><dt>content_hash</dt><dd id="ctxContent">—</dd><dt>trace_hash</dt><dd id="ctxTrace">—</dd><dt>previous</dt><dd id="ctxProviders">—</dd></dl></section><section class="field-panel open-panel"><strong>Dernière lecture</strong><pre id="lastJson" class="json-view">—</pre></section></aside></section>
<footer class="footer"><span>T^AI LAB · <?=tai_h((string)$config['version'])?></span><span>TAI = access marker · FREE ONLY · PUBLIC DATA ONLY</span></footer>
<?php tai_foot('lab'); ?>
